
model:
  _target_: dlmi.models.moe_model.MOEModel

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam

dataset_type: "MILDataset"

# Training parameters
train: 
  lr_cnn: 1e-3
  lr_mlp: 1e-2
  lr_final: 1e-2
  batch_size : 5
  num_epochs: 50
  weight_decay: 0 #0.0005
  beta1: 0.9
  beta2: 0.999
  freeze_cnn: True

# Experiment parameters
exp: 
  name: "Classification"
  data_path: "/../../data/raw/raw" 
  checkpoint: "models/linear"
  seed: 10 # 15 0.82 #29 0.92
  tune:
    enabled: false
    num_samples: 20

# mlflow parameters
mlflow:
  runname: ${exp.name} # Take the value of exp.name

job:
    chdir: true