
model:
  _target_: dlmi.models.final_model.FinalModel

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam

# dataset_type: "MiniDataset"

# Training parameters
train: 
  lr: 1e-4
  batch_size : 1
  num_epochs: 20
  weight_decay: 0 #0.0005
  beta1: 0.9
  beta2: 0.999
  freeze_cnn: True

# Experiment parameters
exp: 
  name: "Classification"
  data_path: "/data/raw/" 
  checkpoint: "models/linear"
  seed: 29
  tune:
    enabled: false
    num_samples: 20

# mlflow parameters
mlflow:
  runname: ${exp.name} # Take the value of exp.name

job:
    chdir: true