
model:
  _target_: dlmi.models.cnn_model.CNNModel 

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam

# Training parameters
train: 
  lr: 1e-4
  batch_size : 2
  num_epochs: 20
  weight_decay: 0

# Experiment parameters
exp: 
  name: "Classification"
  data_path: "/data/raw/" 
  checkpoint: "models/linear"
  seed: 10

# mlflow parameters
mlflow:
  runname: ${exp.name} # Take the value of exp.name

job:
    chdir: true