
model:
  _target_: dlmi.models.models.LeNet 

criterion:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.Adam

# Training parameters
train: 
  lr: 1e-3
  batch_size : 10
  num_epochs: 4

# Experiment parameters
exp: 
  name: "Classification"
  data_path: "/data/raw/" 
  checkpoint: "models/linear"
  seed: 0

# mlflow parameters
mlflow:
  runname: ${exp.name} # Take the value of exp.name

job:
    chdir: true